#server:
  #port: 8090
logging:
  level:
    root: INFO
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate: 
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/curso_spring_boot
    username: root
    password: paco
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-circular-references: true
  